// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjs1lTxr7WKRDPpwBrPoqnYmoeXLVBbBA',
    appId: '1:202651502864:web:3a4cf949a9f0b907833d95',
    messagingSenderId: '202651502864',
    projectId: 'ontrigo-6c2b8',
    authDomain: 'ontrigo-6c2b8.firebaseapp.com',
    storageBucket: 'ontrigo-6c2b8.appspot.com',
    measurementId: 'G-74E1VT05FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Ed-eTlW2D0efkyuGvGbi4yOzHM6WmhI',
    appId: '1:202651502864:android:6ea632ec49175c55833d95',
    messagingSenderId: '202651502864',
    projectId: 'ontrigo-6c2b8',
    storageBucket: 'ontrigo-6c2b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsxf2-QU7iX1QPaBEr2PpVb7uBOK_AVWM',
    appId: '1:202651502864:ios:265cb402965db0e0833d95',
    messagingSenderId: '202651502864',
    projectId: 'ontrigo-6c2b8',
    storageBucket: 'ontrigo-6c2b8.appspot.com',
    iosClientId: '202651502864-efr3to2pp4hfo2g7rlh99jbdq1ih8hun.apps.googleusercontent.com',
    iosBundleId: 'com.example.ontrigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsxf2-QU7iX1QPaBEr2PpVb7uBOK_AVWM',
    appId: '1:202651502864:ios:265cb402965db0e0833d95',
    messagingSenderId: '202651502864',
    projectId: 'ontrigo-6c2b8',
    storageBucket: 'ontrigo-6c2b8.appspot.com',
    iosClientId: '202651502864-efr3to2pp4hfo2g7rlh99jbdq1ih8hun.apps.googleusercontent.com',
    iosBundleId: 'com.example.ontrigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjs1lTxr7WKRDPpwBrPoqnYmoeXLVBbBA',
    appId: '1:202651502864:web:e8a51d424d0aa6ec833d95',
    messagingSenderId: '202651502864',
    projectId: 'ontrigo-6c2b8',
    authDomain: 'ontrigo-6c2b8.firebaseapp.com',
    storageBucket: 'ontrigo-6c2b8.appspot.com',
    measurementId: 'G-FX73LTYLZM',
  );
}
